version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  ignore:
  - dependency-name: Xamarin.UITest
    versions:
    - 3.0.13
    - 3.0.14
    - 3.0.15
    - 3.0.16
  - dependency-name: Microsoft.NETCore.Platforms
    versions:
    - 5.0.0
    - 5.0.1
  - dependency-name: Microsoft.AppCenter.Analytics
    versions:
    - 4.1.0
  - dependency-name: Microsoft.AppCenter
    versions:
    - 4.1.0
  - dependency-name: Microsoft.AppCenter.Crashes
    versions:
    - 4.1.0
