name: Build Xamarin Project

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  android:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - name: Build Android Project with msbuild
        run: |
          nuget install Droid/packages.config  -OutputDirectory packages/
          nuget install iOS/packages.config  -OutputDirectory packages/
          nuget install UITest/packages.config  -OutputDirectory packages/
          msbuild Droid/sampleAppXamarin.Droid.csproj

  ios:
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - name: Build iOS Project with msbuild
        run: |
          nuget install Droid/packages.config  -OutputDirectory packages/
          nuget install iOS/packages.config  -OutputDirectory packages/
          nuget install UITest/packages.config  -OutputDirectory packages/
          msbuild iOS/sampleAppXamarin.iOS.csproj
